[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://campspot-backend.onrender.com/api"
  VITE_APP_NAME = "CampSpot"
  VITE_ENVIRONMENT = "production"

[[redirects]]
  from = "/api/*"
  to = "https://campspot-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
