version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: camping-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    networks:
      - camping-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: camping-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - camping-network
    restart: unless-stopped

networks:
  camping-network:
    driver: bridge

volumes:
  node_modules:
