version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: campspot-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://ahmed:15963@cluster0.6ookgvr.mongodb.net/camping-app?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=b-86R9KOZbbWiCf9xd-9rIps-aCaqohz
      - CORS_ORIGINS=https://campspot12-h6zhy2uue-ahmedmouelhis-projects.vercel.app
    ports:
      - "5000:5000"
    networks:
      - camping-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campspot-frontend
    environment:
      - PORT=80
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - camping-network
    restart: unless-stopped

networks:
  camping-network:
    driver: bridge
