services:
  # Backend API Service on Render
  - type: web
    name: campspot-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://ahmed:15963@cluster0.6ookgvr.mongodb.net/camping-app?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: b-86R9KOZbbWiCf9xd-9rIps-aCaqohz
      - key: CORS_ORIGINS
        value: https://campspot-frontend.vercel.app
